_includes/header.html, _includes/platformcards.html, _includes/scripts.html, _includes/styles.html
=> Includes: Use {% link %} for local assets

_wiki/FAQ/Linux.md
=> Wiki: Linux/FAQ: Add breaks

_config.yml, index.md
This details the config file with comments, and updates some values to what they were intended to be.
=> Clean up config file and use values as intended

_includes/fix-fouc.html, _includes/scripts.html, _includes/styles.html, _layouts/default.html, _layouts/wikipage.html, _wiki/Development/Configurations.md, _wiki/Documentation/Logs.md, _wiki/Documentation/UdevRules.md, _wiki/FAQ/General.md, _wiki/Install/Linux.md, _wiki/Install/Windows.md, assets/fix-fouc.css, assets/js/markdown-inject.js, assets/site.css
Added more margin. Converted some `<small>` elements to markdown blockquote. Also injected table class to markdown tables.
- Fixes #5
=> Improve layout

CNAME, _config.yml
Reverts OpenTabletDriver/opentabletdriver.github.io#27
=> Revert "Remove CNAME" to update DNS

_wiki/Documentation/UdevRules.md
- Fix syntax error
- Retrigger udev (there should be no issue doing this as udev just queues these operations)
=> Fix udev rule scripts

_wiki/FAQ/Linux.md, _wiki/FAQ/MacOS.md, _wiki/FAQ/Windows.md
- Renamed Troubleshooting to "My tablet is supported but not detected?". Also made sure that they are aware of the section of the same title from General.
- Used unordered list where it makes more sense.
=> Improve formatting of some sections

_wiki/FAQ/Windows.md
=> Simplify title

.github/workflows/jekyll.yml
This allows us to test pull requests and commits for validity
Fixes #58
=> Add Jekyll CI

_includes/platformcard.html
We'll do it like this for now until we find a better solution.
=> Fix links from platform cards

.github/workflows/jekyll.yml, _config.yml, run-tests.sh, tests/check-site-paths/check-site-paths.sh
This adds a test that checks whether the site has some predefined paths available, like /Install/Windows and index.html etc.
It also adds a slightly less important test that checks whether Wiki pages are correctly mapped.
=> Test site paths

_includes/platformcard.html, _includes/platformcards.html
Fixes the platform cards on /Wiki
=> Fix captures and use absolute_url filter

_layouts/wikipage.html
Forgot to rebase and remove that now-unused ID...
=> Remove unused ID

site/_config.yml, site/_data/wiki/title-remaps.json, site/_layouts/wiki.html, site/_wiki/Install/Linux.md, site/_wiki/Install/MacOS.md, site/_wiki/Install/Windows.md
This should simplify any potential wiki structure changes
=> Refactor wiki logic

site/_wiki/FAQ/Windows.md
Fixes OpenTabletDriver/opentabletdriver.github.io#49
=> FAQ/Windows: Explain `userdata` in depth

site/_wiki/Documentation/RequiredPermissions.md
This should result in slightly better readability
=> wiki/ReqPermissions: Convert MacOS required permissions to table

site/_wiki/Documentation/RequiredPermissions.md, site/_wiki/FAQ/General.md, site/_wiki/FAQ/Linux.md, site/_wiki/FAQ/LinuxAppSpecific.md, site/_wiki/FAQ/ModelSpecific.md, site/_wiki/FAQ/Windows.md, site/_wiki/FAQ/WindowsAppSpecific.md, site/_wiki/Install/Linux.md, site/_wiki/Install/MacOS.md, site/_wiki/Install/Windows.md
Assorted changes that were picked out of a recent "chaos branch".
This reformats some sections and rewrites their contents. The fundamental meaning of the content is not intended to have changed.
=> wiki cleanup: Generic rewrites or additions

site/assets/js/inject-anchors.js
=> js/inject-anchors: Use optional chaining

.markdownlint.yaml, site/_wiki/Development/Configurations.md, site/_wiki/Documentation/Logs.md, site/_wiki/Documentation/RequiredPermissions.md, site/_wiki/FAQ/Linux.md, site/_wiki/FAQ/MacOS.md, site/_wiki/FAQ/Windows.md, site/_wiki/FAQ/WindowsAppSpecific.md, site/_wiki/Install/Linux.md, site/_wiki/Install/Windows.md, site/assets/css/site.scss, site/assets/js/markdown-inject.js
=> Use Bootstrap alerts to style blockquotes

site/_includes/wiki/header.html, site/_sections/Framework.md, site/_wiki/Development/Configurations.md, site/_wiki/Documentation/CommandLine.md, site/_wiki/Documentation/Logs.md, site/_wiki/FAQ/General.md, site/_wiki/FAQ/Linux.md, site/_wiki/FAQ/LinuxAppSpecific.md, site/_wiki/FAQ/MacOS.md, site/_wiki/FAQ/ModelSpecific.md, site/_wiki/FAQ/Windows.md, site/_wiki/Install/Linux.md, site/_wiki/Install/MacOS.md, site/_wiki/Install/Windows.md, site/assets/css/site.scss
=> Add counters

site/_data/links.json, site/_wiki/Install/Linux.md
Not so sure about formatting, but I guess that's it?
Related to #40. There are a few more RPM-based distros, but I am not sure if we need to cover more of them.
=> Add openSUSE installation steps

site/_wiki/Install/Linux.md
=> Install/Linux: Add initramfs update to Fedora instructions

site/assets/css/site.scss
Brings back font sizes from before #158 and down sized table of contents'.
=> Adjust font sizes for headings and table of contents

site/_wiki/Development/Configurations.md
This should reduce confusion as to what we mean
=> Rename 'Horizontal Resolution' (and vertical) to 'MaxX'

site/_wiki/FAQ/General.md
=> FAQ/General: Add OpenTabletDriver is sensitive to resolution changes

site/_wiki/Development/Configurations.md
=> wiki configurations: Update 'Interface' attributes to new standard

site/Gemfile, site/Gemfile.lock
=> Update Bootstrap and Bootswatch to 5.3.3

site/_layouts/redirect.html, site/_sections/Discord.md
=> Add Discord toplevel redirect

site/_data/links.json, site/_includes/header.html
=> Header: Add Website Github link

site/_wiki/FAQ/Linux.md
Fixes https://github.com/OpenTabletDriver/opentabletdriver.github.io/issues/232
=> FAQ/Linux: Add note about DE mapping virtual device in multi-monitor setups

.github/workflows/deploy.yml, .github/workflows/jekyll-build-workflow.yml, .github/workflows/site-workflow/action.yml
Fixes #245
Some workflows aren't testable from this PR, we should keep a close eye on the deploy action when merging.
=> workflows: Update all workflows to latest

site/_includes/tablets.md
Should be merged after release.
=> Update supported tablets for 0.6.5.1

site/_wiki/Install/Windows.md
how did we miss this for months lol
=> Fix wrong mention of dotnet version

site/_wiki/Install/Linux.md
Untested as I do not have a dev env for ruby because ruby packaging sucks on arch, surely the docs i read were right
=> fix deb name

site/_includes/tablets.md
=> _include/tablets.md: Update for 0.6.6.0
