OpenTabletDriver/opentabletdriver.github.io

_includes/filterjs.html, _layouts/plugins.html
This is more intuitive for the user - selecting a driver version will now show all compatible plugins by default.
New default look:
Previously, it would show every single plugin in the database, and only filter plugins exactly matching the driver version.
Also fixes #14
=> Plugins: Update filtering, style and add driver compatibility

_includes/filterjs.html, _includes/searchjs.html
This allows /Tablets and /Plugins to use the `search=searchstring` query parameter
Fixes #15
=> Reintroduce search query strings

README.md
Correctly formatted README.md file with consistent formatting and linting. Also, included `<hr/>` prior to H3. 
Solved Issue #11 
_Screenshot 1_
=>  Consistent Formatting in README Markdown File

CNAME, _config.yml
We can use the old links for support for now
When the site changes DNS over it should redirect to the correct links anyway
This commit can be reverted once DNS is ready to move
=> Remove CNAME

_layouts/plugins.html
Before:
After:
Before:
After:
---
Also removed the extra spans, I'm not sure what it's for but it doesn't affect layout in any way afaict.
=> Make whitespace more consistent around card button

_config.yml
Mostly a parity fix, fast-tracking this change.
=> config: Fix typo in site description

_sections/Framework.md
Draft for multiple reasons:
- DDL links exist, i just don't know if they will break so I haven't included them
- can't find a link for dotnet for osx x86? (did this even exist)?? so i haven't updated it.
- Not sure why we even include "uncommon builds" because we don't even have OTD binaries for these? Users have to compile them for themselves which you haven't included the SDKs or instructions for.
- MacOS builds are self contained, we have no reason to include the dotnet package link here. (we don't link it on the installation guide though).
=> Fix .NET runtime links

_wiki/Documentation/UdevRules.md, _wiki/FAQ/Linux.md, _wiki/Install/Linux.md
- Add instructions for legacy packages.
- Add Fedora instructions.
- Minor tweaks to other install instructions to not rely on systemd service.
- Unload kernel modules on install on Arch Linux.
=> Improve Linux install instructions

_wiki/FAQ/Linux.md
The correct `systemctl` parameter is `--user`, not `user`.
=> Fix systemctl parameter

_includes/header.html, _layouts/wikipage.html
This issue somehow only manifests on some pages, but this commit fixes it completely.
Before:
After:
Before:
`Large (>= 992px)`
`Medium (>= 768px)`
`Small (>= 576px)`
`Extra Small (< 576px)`
After:
`Large (>= 992px)`
`Medium (>= 768px)`
`Small (>= 576px)`
`Extra Small (< 576px)`
=> Fix layout issues

_includes/platformcard.html, _includes/platformcards.html
=> Cleanup and always center platform cards

_includes/header.html, _layouts/default.html, assets/css/site.scss
Nothing changed visually for the whitespace between body and header, but the end of the body did change. Instead of a hardcoded `60px` bottom margin, it's now using `mb-5`.
Before:
After:
=> Simplify body and header whitespace

_includes/scripts.html, _layouts/wikipage.html, _sass/_anchor-blink.scss, assets/css/site.scss, assets/js/inject-anchors.js
Looks like this on hover:
And looks like this when loading directly via link with anchor:
https://github.com/OpenTabletDriver/opentabletdriver.github.io/assets/10338031/51c80b6d-4ce0-4b38-b193-764ac02985cf
I removed jekyll_toc's `inject_anchors` filter since it isn't really working.
- Resolves #50
- Resolves #64
=> Add anchor links

_config.yml
This addresses concerns that title must match path
Resolves #37
Interestingly, `:title` in sections _does_ correspond to path (evident by `/Framework` working both before and after despite its title being `Frameworks`), so doing it this way makes it more clear what we're trying to do without actually changing the functionality.
This change affects `_section` endpoints: `/Framework`, `/Plugins` `/Tablets` `/Wiki` but effectively doesn't change them.
=> sections: Permalink to path

README.md
These lines should have been changed with the Jekyll 4.x merge but were forgotten
Fast merging since this is objectively correct
=> README: Update site paths

.github/dependabot.yml
Closes #36 
This is similar to running `bundle update --all`, which should be run regularly because bleeding edge is cool (and also puts a bunch of faith in our tests working).
=> dependabot: Add weekly Bundler updates

README.md
Modern Ruby installs include Bundler by default, so we technically don't need to advise about rubygems at all.
Improvements are welcome, we could probably even just say that only Ruby is needed, since that is the case?
=> README: Adjust local development steps

.editorconfig, .git-blame-ignore-revs, .github/workflows/linter.yml, .markdownlint.yaml, README.md, TODO.md, site/_plugins/rouge-logoutput-lexer.rb, site/_wiki/Documentation/RequiredPermissions.md, site/_wiki/FAQ/General.md, site/_wiki/FAQ/Linux.md, site/_wiki/FAQ/Windows.md, site/_wiki/FAQ/WindowsAppSpecific.md, site/_wiki/Install/Linux.md, site/_wiki/Install/Windows.md, site/index.md
Lints markdown with [`markdownlint-cli`](https://github.com/igorshubovych/markdownlint-cli) with the GitHub action [nosborn/github-action-markdown-cli](https://github.com/nosborn/github-action-markdown-cli).
Uses my local fork until a PR is merged that we need: nosborn/github-action-markdown-cli#64
Notes
- ~~Fragments to other pages does not seem to be verified (e.g. `{% link /index.md %}#myid %}`)~~ less of a concern with #76
- Code blocks after `<ol>`'s are not linted for indentation. We can't reasonably lint for this even with a custom rule so I've tried to make sure code blocks are indented correctly with this PR.
=> Lint markdown in PRs

site/_config.yml
This should allow us to catch use of undefined filters (e.g. `{{ content | toc }}`) at compile time
=> config: Use strict filters

site/_layouts/plugins.html
Uses the new `MaxSupportedDriverVersion` field in plugin metadata to override our default compatibility check.
=> Fix plugin max version

.github/workflows/linter.yml, README.md, site/_includes/appdata-location.md, site/_wiki/Documentation/Logs.md, site/_wiki/FAQ/General.md
=> wiki/Logs: Split exception log location into its own section

.github/workflows/jekyll.yml, .github/workflows/linter.yml
Not having it is causing PR tests to temporarily show a failed test, as the Jekyll build needs to be on a site with Github Pages active.
Put differently, any push (even on forks) would result in the Jekyll workflow failing. We could leave the Linter workflow untouched, but it is changed for consistency in case the Linter workflow is expanded in scope.
Also fixes #121
=> workflows: Restrict actions push conditions to just 'main'

site/assets/js/inject-anchors.js
This also changes the behavior of the animation to span the entire block, rather than rewriting the block text to a span, and then animating the span.
This is an intentional stylistic change since I felt the previous method was not obvious enough.
This also fixes animations 'eating' the anchor link
Fixes #72
=> inject-anchors: Refactor and enable blink on 'hashchange'

site/_includes/scripts.html, site/_includes/styles.html, site/_plugins/get-asset.rb
This helps avoid caches incorrectly returning "304 Not Changed". Some brief testing seems to indicate that query strings does correctly cause a cache hit on our webserver (Cloudflare?)
We can also consider moving the hosting (haha) to something like Cloudflare Pages which allows us to control HTTP headers.
This solution isn't optimal, we should be using a Jekyll hook to change the filename and the defined path in the HTML, since caching on query strings is not clearly defined across caching proxies.
=> Cache busting CSS/JS using a query string

site/_wiki/Install/Linux.md
=> Fix formatting in openSUSE guide header

site/_layouts/frontpage.html
This was reversing the array for no reason. We can just pick the last element directly.
=> (minor) Optimize version getting for Frontpage

site/_wiki/Documentation/RequiredPermissions.md
A user following the wiki is likely going to miss the fact that the modules might not be unloaded, as the module blacklist has not yet had a chance to apply on a fresh install.
This should ensure that users unload them before following the complicated udev and module blacklist steps below it
=> Add rmmod steps to Doc/RequiredPermissions

site/_wiki/FAQ/LinuxAppSpecific.md
Helps with the GIMP portion of #52
First commit (668b479) should be good for reuse for anyone else wanting to append instructions in a separate PR
Leaving as draft until it is verified that the input device is correct for X11
=> Add GIMP instructions to Linux App FAQ

site/_wiki/Install/Linux.md
A source package now exists for OpenTabletDriver on gentoo, it is in a much better state, uses the latest version of OTD,  the scripts are updated, etc etc.
I haven't personally tested these instructions but considering that it still uses the keyword these instructions should work.
The only "problem" I see here is that its a different maintainer, which maybe we should note somewhere?
Also even on systemd no systemd service is provided (on both packages), so we should probably relink the section to point directly at the other init systems section or place a note elsewhere. Not a biggie though.
Here is a link to the new package: https://github.com/gentoo/guru/tree/master/x11-drivers/OpenTabletDriver
=> Use better maintained source opentabletdriver gentoo package

site/Gemfile, site/Gemfile.lock, site/_includes/appdata-location.md, site/_includes/styles.html, site/_layouts/default.html, site/_layouts/tablets.html, site/_plugins/inject-scss-gems.rb, site/_wiki/Development/Configurations.md, site/_wiki/Documentation/CommandLine.md, site/_wiki/Documentation/RequiredPermissions.md, site/_wiki/FAQ/General.md, site/assets/css/site.scss
Darkly is still a predominantly dark-theme skin, but has small variations between dark and light mode.
A lot of color and pixel-specific settings have been removed as the stock theme is actually surprisingly close what we want.
Additionally, having these was hindering correct light/dark mode display.
Removing these also allows us to be more flexible with which Bootswatch themes we can use.
Many definitions have been moved around to better fit the nesting of SCSS, reducing clutter and
increasing readability.
Supersedes #157
Supersedes #154
Fixes #33
Fixes #151
=> Refactor SCSS

site/_wiki/Documentation/RequiredPermissions.md, site/_wiki/Install/Linux.md
This ensures that the user actually unloads all driver modules, in case only 1 of the 2 commands was run
Fixes #164
=> Wiki/Linux: Simplify `rmmod` commands

site/_wiki/Documentation/Logs.md, site/_wiki/FAQ/General.md
OpenTabletDriver removed the `daemon.log` crash file and instead logs everything to a single folder.
See OpenTabletDriver/OpenTabletDriver#3100 for more information
Fixes #152
=> FAQ: Update to OTD's new logging method

site/_wiki/Install/MacOS.md
This should always be required so it makes sense to mention it in the main install guide rather than only in the faq. The permissions can be concerning to some users so it's better to put it upfront rather than make the user dig around for it.
=> Mention required permissions in macos install

site/_wiki/FAQ/MacOS.md
It is possible to hit an error like this when trying to open OTD:
Apple has official docs for resolving this so we can link there. Apple has pages for other variants of this error but they require the exact same steps.
=> Add apple verification error to macos faq

site/_wiki/FAQ/Linux.md
OpenTabletDriver v0.6.5.0 now ships with the libinput smoothing disabled in packaging. This commit adds details for how to check whether this is applied correctly, but also keeps pre-v0.6.5.0 instructions intact for users still on earlier versions.
Fixes #226
=> Reword libinput smoothing fix section for v0.6.5.0

site/_wiki/FAQ/WindowsAppSpecific.md
Now that GIMP has moved on from calling GIMP 3 dev builds "GIMP 2.99" and instead has release candidate builds (GIMP 3.0 RCx) it makes sense to note GIMP 3 here.
=> Change GIMP 2.99 to GIMP 3 for windows app specific

site/_wiki/FAQ/Linux.md
=> FAQ/Linux: fix 'liblinput' typo

site/_wiki/FAQ/General.md
=> Add 2024 Gaomon driver conversion formula

site/assets/css/site.scss, site/assets/js/inject-anchors.js
Counters weren't working with H5's and H6's, this PR fixes that. H5 fix needed in #173 to fix styling.
=> CSS counter support for h5 and h6

.ecrc, site/_includes/wiki/arch-install-steps.md, site/_includes/wiki/arch-makepkg-commands.txt, site/_includes/wiki/arch-makepkg-steps.txt, site/_includes/wiki/arch-regen-commands.txt, site/_wiki/Install/Linux.md
I've also split the Arch install steps into includes. This reduces the amount of duplicated text in the repository, and allows us to easier support other variants of Arch Linux.
Helps with some concerns in #93 but does not fix it entirely.
=> Add EndeavourOS install instructions
